### ISSUE TITLE
Add support for after success and after failure tasks

### ISSUE THREAD

**Issue by relekang** [frigg/frigg-worker#113]
This is useful to initiate releases or deployments.

**Comment by relekang** [comment]
@frecar What do yo think about changing the task config structure to something like:
```yaml
tasks:
  setup:
    - npm install
  tests:
    - npm test
  after_success:
    - npm run semantic-release
```
