### ISSUE TITLE
Preview presets

### ISSUE THREAD

**Issue by relekang** [frigg/frigg-worker#90]
Predefined presets with tasks to deploy previews to make it easier to setup and mantain preview configuration for standard projects.

Should have a list of tasks and the "daemon task" and run preview tasks defined in frigg config after the preset tasks before running the daemon task.

Example 

```yaml
preview:
  preset: django
  tasks:
   - python manage.py loaddata fixtures/preview.json
```
